version: "3.8"

services:
  app:
    build: .
    container_name: php-task
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./php/conf.d/xdebug.ini:/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
